/**
 * Claw Calendar - API 类型定义
 * 统一前后端数据类型，确保 API 响应格式一致
 */

// ============ 错误码定义 ============

const ErrorCode = {
  // 认证错误 (40x)
  UNAUTHORIZED: 'UNAUTHORIZED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  INVALID_TOKEN: 'INVALID_TOKEN',

  // 权限错误 (403)
  FORBIDDEN: 'FORBIDDEN',
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',

  // 资源错误 (404)
  NOT_FOUND: 'NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  CALENDAR_NOT_FOUND: 'CALENDAR_NOT_FOUND',
  EVENT_NOT_FOUND: 'EVENT_NOT_FOUND',

  // 验证错误 (422)
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_EMAIL: 'INVALID_EMAIL',
  INVALID_PASSWORD: 'INVALID_PASSWORD',
  INVALID_DATE: 'INVALID_DATE',

  // 业务错误 (409)
  EMAIL_EXISTS: 'EMAIL_EXISTS',
  CALENDAR_LIMIT_EXCEEDED: 'CALENDAR_LIMIT_EXCEEDED',
  EVENT_CONFLICT: 'EVENT_CONFLICT',

  // 服务器错误 (500)
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
  ENCRYPTION_ERROR: 'ENCRYPTION_ERROR',
};

module.exports = { ErrorCode };
